### ISSUE TITLE
Implement read and write support for new Astarte Container interfaces

### ISSUE THREAD

**Issue by rbino** [edgehog-device-manager/edgehog#614]
See https://github.com/edgehog-device-manager/edgehog-astarte-interfaces/pull/64/.

This is a meta issue, the person handling each interface should create a new issue dedicated to it and auto-assign it to themselves so we can keep track of what stuff is being worked on.

For Device Owned interfaces the implementation should:
- Have a struct module with a `get` function ([e.g.](https://github.com/edgehog-device-manager/edgehog/blob/main/backend/lib/edgehog/astarte/device/system_status.ex)) + a behaviour to mock the API calls in tests ([e.g.](https://github.com/edgehog-device-manager/edgehog/blob/main/backend/lib/edgehog/astarte/device/system_status/behaviour.ex)) in the `Astarte` context
- A calculation on the `Device` resource to retrieve the value for a specific device (see [here](https://github.com/edgehog-device-manager/edgehog/blob/1cd7df0671e9ad40c0bf17c4fb5316ad96e497b0/backend/lib/edgehog/devices/device/calculations/astarte_interface_value.ex#L104) and [here](https://github.com/edgehog-device-manager/edgehog/blob/1cd7df0671e9ad40c0bf17c4fb5316ad96e497b0/backend/lib/edgehog/devices/device/device.ex#L399))
- An associated Ash type ([e.g.](https://github.com/edgehog-device-manager/edgehog/blob/main/backend/lib/edgehog/devices/device/types/system_status.ex)) that maps to an Absinthe GraphQL object ([e.g.](https://github.com/edgehog-device-manager/edgehog/blob/1cd7df0671e9ad40c0bf17c4fb5316ad96e497b0/backend/lib/edgehog_web/schema/astarte_types.ex#L90))
- A test verifying that the GraphQL `device` query is able to read the value [here](https://github.com/edgehog-device-manager/edgehog/blob/1cd7df0671e9ad40c0bf17c4fb5316ad96e497b0/backend/test/edgehog_web/schema/query/device_test.exs#L327)

For Server Owned interfaces (i.e. "commands") the implementation should:
- Have a struct module with a `$appropriate_action` function ([e.g.](https://github.com/edgehog-device-manager/edgehog/blob/main/backend/lib/edgehog/astarte/device/led_behavior.ex), the name is meh, I'd call it `set_behavior` today) + a behaviour to mock the API calls in tests ([e.g.](https://github.com/edgehog-device-manager/edgehog/blob/main/backend/lib/edgehog/astarte/device/led_behavior/behaviour.ex)) in the `Astarte` context
- A manual update action on the `Device` resource to send the command (see [here](https://github.com/edgehog-device-manager/edgehog/blob/main/backend/lib/edgehog/devices/device/manual_actions/set_led_behavior.ex) and [here](https://github.com/edgehog-device-manager/edgehog/blob/1cd7df0671e9ad40c0bf17c4fb5316ad96e497b0/backend/lib/edgehog/devices/device/device.ex#L222))
- For now, no tests are needed (since the action will probably be exposed not as a single mutation but will be used in a complex mutation e.g. `createApplicationRelease`)

Lower priority interfaces can be handled at the end.

Device-owned interfaces:
- [x] io.edgehog.devicemanager.apps.AvailableContainers
- [x] io.edgehog.devicemanager.apps.AvailableDeployments
- [x] io.edgehog.devicemanager.apps.AvailableImages
- [x] io.edgehog.devicemanager.apps.DeploymentEvent

Server-owned interfaces:
- [x] io.edgehog.devicemanager.apps.CreateContainerRequest
- [x] io.edgehog.devicemanager.apps.CreateDeploymentRequest
- [x] io.edgehog.devicemanager.apps.CreateImageRequest
- [x] io.edgehog.devicemanager.apps.DeploymentCommand
- [x] io.edgehog.devicemanager.apps.DeploymentUpdate

Lower priority:
- [x] io.edgehog.devicemanager.apps.AvailableNetworks
- [x] io.edgehog.devicemanager.apps.AvailableVolumes
- [x] io.edgehog.devicemanager.apps.CreateNetworkRequest
- [x] io.edgehog.devicemanager.apps.CreateVolumeRequest

**Comment by noaccOS** [comment]
all interfaces have successfully been merged
